<Project Sdk="Microsoft.NET.Sdk">
  <!-- 
  Imports silksong path properties only if present in order to allow CI builds. The file should be gitignored.
  If you are checking out from git and need to create a new one, you can use `dotnet new silksongpath` to generate one.
  -->
  <Import Condition="Exists('SilksongPath.props')" Project="SilksongPath.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisMode>recommended</AnalysisMode>
    <!-- Ignore warning about processor architecture mismatch with PlayMaker ConditionalExpression -->
    <NoWarn>$(NoWarn);MSB3270</NoWarn>

    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/mich101mich/SaveFileManager</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup Condition=" '$(DesignTimeBuild)' != 'true' And '$(CI)' != 'true' ">
    <Reference Include="0Harmony">                          <HintPath>$(BepInExDllFolder)\0Harmony.dll</HintPath></Reference>
    <Reference Include="BepInEx">                           <HintPath>$(BepInExDllFolder)\BepInEx.dll</HintPath></Reference>
    <Reference Include="Assembly-CSharp">                   <HintPath>$(SilksongDllFolder)\Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="TeamCherry.SharedUtils">            <HintPath>$(SilksongDllFolder)\TeamCherry.SharedUtils.dll</HintPath></Reference>
    <Reference Include="UnityEngine">                       <HintPath>$(SilksongDllFolder)\UnityEngine.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule">            <HintPath>$(SilksongDllFolder)\UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.InputLegacyModule">     <HintPath>$(SilksongDllFolder)\UnityEngine.InputLegacyModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.UI">                    <HintPath>$(SilksongDllFolder)\UnityEngine.UI.dll</HintPath></Reference>
  </ItemGroup>

  <ItemGroup Condition=" '$(DesignTimeBuild)' == 'true' And '$(CI)' != 'true' ">
    <ProjectReference Include="$(BepInExSourceFolder)\0Harmony\0Harmony.csproj" />
    <ProjectReference Include="$(BepInExSourceFolder)\BepInEx\BepInEx.csproj" />
    <ProjectReference Include="$(SilksongSourceFolder)\TeamCherry.SharedUtils\TeamCherry.SharedUtils.csproj" />
    <ProjectReference Include="$(SilksongSourceFolder)\Assembly-CSharp\Assembly-CSharp.csproj" />
    <ProjectReference Include="$(SilksongSourceFolder)\UnityEngine\UnityEngine.csproj" />
    <ProjectReference Include="$(SilksongSourceFolder)\UnityEngine.CoreModule\UnityEngine.CoreModule.csproj" />
    <ProjectReference Include="$(SilksongSourceFolder)\UnityEngine.InputLegacyModule\UnityEngine.InputLegacyModule.csproj" />
    <ProjectReference Include="$(SilksongSourceFolder)\UnityEngine.UI\UnityEngine.UI.csproj" />
  </ItemGroup>

  <ItemGroup Condition=" '$(CI)' == 'true' ">
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="HarmonyX" Version="2.9.0" />
    <PackageReference Include="UnityEngine.Modules" Version="6000.0.50" IncludeAssets="compile" />
    <PackageReference Include="Silksong.GameLibs" Version="*-*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Folder Remove="thunderstore/temp;thunderstore/dist" />
    <None Include="README.md" Pack="True" PackagePath="README.md" />
    <None Include="thunderstore/icon.png" Pack="True" PackagePath="icon.png" />
  </ItemGroup>

  <Target Name="CopyAndPackageMod" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <Binaries Include="$(TargetPath)" LocalDir="/" PackDir="/" />
      <Binaries Include="$(TargetDir)/$(TargetName).pdb" LocalDir="/" PackDir="/" />
    </ItemGroup>
    <PropertyGroup>
      <ThunderstoreDir>$(ProjectDir)/thunderstore</ThunderstoreDir>
    </PropertyGroup>

    <!-- Local install -->
    <Copy SourceFiles="@(Binaries)" DestinationFolder="$(SilksongPluginsFolder)/$(AssemblyTitle)/%(Binaries.LocalDir)" Condition="'$(SilksongPluginsFolder)' != '' And Exists('$(SilksongPluginsFolder)')" />

    <!-- Thunderstore packaging -->
    <!-- <RemoveDir Directories="$(ThunderstoreDir)/temp;$(ThunderstoreDir)/dist" /> -->
    <!-- <MakeDir Directories="$(ThunderstoreDir)/temp" /> -->
    <!-- <Copy SourceFiles="@(Binaries)" DestinationFolder="$(ThunderstoreDir)/temp/%(Binaries.PackDir)" /> -->
    <!-- <PropertyGroup>
      <ThunderstorePkgVersion>$([System.String]::Copy($(Version)).Split('-')[0])</ThunderstorePkgVersion>
    </PropertyGroup> -->
    <!-- <Exec Command="dotnet tool restore" /> -->
    <!-- <Exec Command="dotnet tcli build \-\-config-path &quot;$(ThunderstoreDir)/thunderstore.toml&quot; \-\-package-name &quot;$(AssemblyTitle)&quot; \-\-package-version $(ThunderstorePkgVersion)" StandardOutputImportance="High" StandardErrorImportance="High" /> -->
  </Target>
</Project>
