name: Localization Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      # Run scripts\check_language_files.py
      - name: Check language files
        run: |
          python3 scripts/check_language_files.py
